version: '2'
services:
  serviciotecnicoflota-app:
    image: serviciotecnicoflota
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://serviciotecnicoflota-postgresql:5432/ServicioTecnicoFlota
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://serviciotecnicoflota-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://serviciotecnicoflota-elasticsearch:9200
    ports:
      - 8080:8080
  serviciotecnicoflota-postgresql:
    extends:
      file: postgresql.yml
      service: serviciotecnicoflota-postgresql
  serviciotecnicoflota-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: serviciotecnicoflota-elasticsearch
